version: '3.8'

services:
  # Aplicação React - Produção
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_ENVIRONMENT=${ENVIRONMENT:-production}
        - VITE_APP_VERSION=${APP_VERSION:-1.0.0}
        - VITE_BUILD_TIMESTAMP=${BUILD_TIMESTAMP}
        - VITE_LOGROCKET_APP_ID=${VITE_LOGROCKET_ID}
        - VITE_LOGROCKET_PROJECT_NAME=fiap-react-deploy
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    labels:
      # Labels para Coolify
      - "coolify.managed=true"
      - "coolify.version=1.0"
      - "coolify.name=fiap-react-deploy"
      - "coolify.description=Status App FIAP - Painel de Diagnóstico do Deploy"
      - "coolify.environment=production"
      # Labels para Traefik (configurados pelo Coolify)
      - "traefik.enable=true"
      - "traefik.http.routers.fiap-react-prod.rule=Host(`${PROD_DOMAIN:-app.gerson-prudencio.com.br}`)"
      - "traefik.http.routers.fiap-react-prod.entrypoints=websecure"
      - "traefik.http.routers.fiap-react-prod.tls=true"
      - "traefik.http.routers.fiap-react-prod.tls.certresolver=letsencrypt"
      - "traefik.http.services.fiap-react-prod.loadbalancer.server.port=8080"
      # Headers de segurança
      - "traefik.http.routers.fiap-react-prod.middlewares=security-headers@docker"
      - "traefik.http.middlewares.security-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.security-headers.headers.sslRedirect=true"
      - "traefik.http.middlewares.security-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.security-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.security-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.security-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.security-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.security-headers.headers.stsPreload=true"

# Volumes para persistência (se necessário no futuro)
volumes:
  app-data:
    driver: local
    labels:
      - "coolify.managed=true" 