version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_ENVIRONMENT=${ENVIRONMENT:-production}
        - VITE_APP_VERSION=${APP_VERSION:-1.0.0}
        - VITE_BUILD_TIMESTAMP=${BUILD_TIMESTAMP}
        - VITE_LOGROCKET_APP_ID=${VITE_LOGROCKET_ID}
        - VITE_LOGROCKET_PROJECT_NAME=fiap-react-deploy
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - ENVIRONMENT=${ENVIRONMENT:-production}
    ports:
      - "5001:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app-https.rule=Host(`app.gerson-prudencio.com.br`) && PathPrefix(`/`)"
      - "traefik.http.routers.app-https.entryPoints=https"
      - "traefik.http.routers.app-https.middlewares=gzip"
      - "traefik.http.routers.app-https.service=app-service"
      - "traefik.http.routers.app-https.tls=true"
      - "traefik.http.routers.app-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.app-http.rule=Host(`app.gerson-prudencio.com.br`) && PathPrefix(`/`)"
      - "traefik.http.routers.app-http.entryPoints=http"
      - "traefik.http.routers.app-http.middlewares=redirect-to-https"
      - "traefik.http.services.app-service.loadbalancer.server.port=8080"
    networks:
      - coolify

volumes:
  app-data:
    driver: local
    labels:
      - "coolify.managed=true"

networks:
  coolify:
    external: true 