version: '3.8'

services:
  fiap-react-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_ENVIRONMENT=dev
        - VITE_APP_VERSION=dev-latest
        - VITE_BUILD_TIMESTAMP=${BUILD_TIMESTAMP}
        - VITE_LOGROCKET_APP_ID=${VITE_LOGROCKET_ID_DEV}
        - VITE_LOGROCKET_PROJECT_NAME=fiap-react-deploy-dev
        - VITE_DEBUG=true
    environment:
      - NODE_ENV=development
      - ENVIRONMENT=dev
      - DEBUG=true
    ports:
      - "5000:8080"
    volumes:
      - ./src:/app/src:ro
      - ./public:/app/public:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    labels:
      - "coolify.managed=true"
      - "coolify.environment=development"
      - "coolify.name=fiap-react-deploy-dev"
      - "coolify.description=Status App FIAP - Ambiente de Desenvolvimento"
      - "traefik.enable=true"
      - "traefik.http.routers.fiap-react-dev.rule=Host(`dev.gerson-prudencio.com.br`)"
      - "traefik.http.routers.fiap-react-dev.entrypoints=websecure"
      - "traefik.http.routers.fiap-react-dev.tls=true"
      - "traefik.http.routers.fiap-react-dev.tls.certresolver=letsencrypt"
      - "traefik.http.services.fiap-react-dev.loadbalancer.server.port=5000"
      - "traefik.http.routers.fiap-react-dev.middlewares=dev-headers@docker"
      - "traefik.http.middlewares.dev-headers.headers.customRequestHeaders.X-Environment=development"
      - "traefik.http.middlewares.dev-headers.headers.customRequestHeaders.X-Debug=true"
    networks:
      - coolify

volumes:
  app-data:
    driver: local
    labels:
      - "coolify.managed=true" 

networks:
  coolify:
    external: true